nodejs:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
os:
  - ubuntu/trusty64
cassandra:
  - 1.2
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - 3.7
build:
  - type: envinject
    properties: |
      TEST_CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION
      JAVA_HOME=$CCM_JAVA_HOME
      CCM_PATH=$HOME/ccm
      JUNIT_REPORT_STACK=1
      JUNIT_REPORT_PATH=.
      multi=mocha-jenkins-reporter=-
  - npm: install
  - npm: run-script ci
    graceful: true
  - script: |
      cd examples
      npm install
      ccm create test_samples -n 1 -b -s -v $TEST_CASSANDRA_VERSION
      node runner.js
      run_rc=$?
      ccm remove
      exit $run_rc
    strict: false
  - xunit: "*.xml"
