schedules:
  commit:
    # per commit job for all branches to run a subset of configs.
    schedule: per_commit
    matrix:
      exclude:
        # Exclude all builds for 6.x.
        - nodejs: ['6']
        # Only build with latest for 4.x and 10.x
        - nodejs: ['4','10']
          cassandra: ['2.1', '2.2', '3.0']
        # Only build with 2.1 and latest for 8.x
        - nodejs: '8'
          cassandra: ['2.2', '3.0']
  nightly:
    # nightly job for primary branches to run all configs.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, master, etc).
      include: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
  adhoc:
    # adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
    schedule: adhoc
    branches:
      exclude: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
nodejs:
  - '4'
  - '6'
  - '8'
  - '10'
os:
  - ubuntu/bionic64/nodejs-driver
cassandra:
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
build:
  - type: envinject
    properties: |
      TEST_CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION
      JAVA_HOME=$CCM_JAVA_HOME
      CCM_PATH=$HOME/ccm
      JUNIT_REPORT_STACK=1
      JUNIT_REPORT_PATH=.
      multi=mocha-jenkins-reporter=-
      SIMULACRON_PATH=$HOME/simulacron.jar
      TEST_TRACE=on
  - npm: install
  - npm: install mocha-jenkins-reporter@0
  - npm: run ci_jenkins
    graceful: true
  - script: |
      cd examples
      npm install
      ccm create test_samples -n 1 -b -s -v $TEST_CASSANDRA_VERSION
      node runner.js
      run_rc=$?
      ccm remove
      exit $run_rc
    strict: false
  - xunit: "*.xml"
