nodejs:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
os:
  - ubuntu/trusty64
cassandra:
  - dse-4.8
  - dse-5.0
build:
  - npm: install
  - script: |
      export TEST_DSE_VERSION=$CCM_VERSION
      export TEST_DSE_BRANCH=$CCM_BRANCH
      export TEST_DSE_DIR=$CCM_INSTALL_DIR
      export JAVA_HOME=$CCM_JAVA_HOME
      export CCM_PATH=$HOME/ccm
      export JUNIT_REPORT_STACK=1
      export JUNIT_REPORT_PATH=.
      npm install kerberos
      npm install mocha-jenkins-reporter
      if [ "$NODEJS_VERSION" != "0.10" ] && [ "$NODEJS_VERSION" != "0.12" ]; then
        npm install -g eslint;
        npm run eslint;
      fi
      npm run ci || true
  - xunit: "*.xml"
