schedules:
  commit:
    # Run short suite on commit
    schedule: per_commit
    matrix:
      exclude:
        # Exclude all builds for Node.js 6
        - nodejs: ['6']
        # Only build DSE 6.0 with Node.js 4
        - nodejs: ['4']
          cassandra: ['dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.7', 'dse-6.8']
        # Only build DSE 6.7 with Node.js 10
        - nodejs: ['10']
          cassandra: ['dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Build all DSE versions with Node.js 8 except DSE 6.0 and DSE 6.7
        - nodejs: ['8']
          cassandra: ['dse-6.0', 'dse-6.7']
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, dse, master, etc).
      include: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
  adhoc:
    # Adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
    schedule: adhoc
    branches:
      exclude: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
nodejs:
  - '4'
  - '6'
  - '8'
  - '10'
os:
  - ubuntu/bionic64/nodejs-driver
cassandra:
  - dse-4.8
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
  - dse-6.8
build:
  - npm: install
  - npm: install mocha-jenkins-reporter@0
  - npm: install kerberos@1
  - npm: install -g eslint@4
  - npm: run eslint
  - script: |
      export TEST_DSE_VERSION=$CCM_VERSION
      export TEST_DSE_BRANCH=$CCM_BRANCH
      export TEST_DSE_DIR=$CCM_INSTALL_DIR
      export JAVA_HOME=$CCM_JAVA_HOME
      export CCM_PATH=$HOME/ccm
      export JUNIT_REPORT_STACK=1
      export JUNIT_REPORT_PATH=.
      npm run ci_jenkins || true
  - xunit: "*.xml"
